"""Helper for ingesting analysis results into SQLite DB.

Provides ``ingest_all(ticker, metrics_path)`` which writes quantitative metrics,
fundamentals and macro data into the corresponding tables using ``INSERT OR REPLACE``.
"""

from __future__ import annotations

import json
import pathlib
import sqlite3
from datetime import datetime, timezone

BASE_DIR = pathlib.Path(__file__).resolve().parents[1]
DB_PATH = BASE_DIR / "investment_lab.db"
DATA_DIR = BASE_DIR / "data"


def _connect() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def _ingest_quantitative(metrics_path: pathlib.Path) -> None:
    data = json.loads(metrics_path.read_text(encoding="utf-8"))
    meta = data.get("meta", {})
    ticker = meta.get("ticker")
    date = meta.get("history_last_date")
    if not ticker or not date:
        raise ValueError("Metrics JSON missing ticker or history_last_date")
    conn = _connect()
    cur = conn.cursor()
    cur.execute(
        "INSERT OR REPLACE INTO quantitative (ticker, date, metrics) VALUES (?, ?, ?)",
        (ticker, date, json.dumps(data, ensure_ascii=False)),
    )
    conn.commit()
    conn.close()


def _ingest_fundamentals(ticker: str) -> None:
    path = DATA_DIR / "fundamentals" / f"{ticker}_fundamentals.json"
    if not path.is_file():
        return
    data = json.loads(path.read_text(encoding="utf-8"))
    collected = data.get("collected_at")
    if isinstance(collected, str) and "T" in collected:
        date = collected.split("T")[0]
    else:
        date = datetime.now(timezone.utc).date().isoformat()
    conn = _connect()
    cur = conn.cursor()
    cur.execute(
        "INSERT OR REPLACE INTO fundamentals (ticker, date, data) VALUES (?, ?, ?)",
        (ticker, date, json.dumps(data, ensure_ascii=False)),
    )
    conn.commit()
    conn.close()


def _ingest_macro() -> None:
    path = DATA_DIR / "macroeconomic" / "macro_data.json"
    if not path.is_file():
        return
    data = json.loads(path.read_text(encoding="utf-8"))
    date = datetime.now(timezone.utc).date().isoformat()
    conn = _connect()
    cur = conn.cursor()
    cur.execute(
        "INSERT OR REPLACE INTO macro (date, data) VALUES (?, ?)",
        (date, json.dumps(data, ensure_ascii=False)),
    )
    conn.commit()
    conn.close()


def _ingest_sentiment(ticker: str) -> None:
    """Calculate a simple sentiment score for *ticker* and store it.

    The function reads ``data/news/{ticker}_news.json`` (generated by
    ``news_collector.py``).  Each article contains ``sentiment_polarity`` and
    ``sentiment_subjectivity`` fields.  For the purpose of the database we
    compute the average polarity of all articles whose ``published`` date falls
    within the last 30 days and store the result with the corresponding date
    (the most recent article date).  If no news file exists or it contains no
    articles, the function silently returns – the ``sentiment`` table will then
    report "无数据" as before.
    """
    news_path = DATA_DIR / "news" / f"{ticker}_news.json"
    if not news_path.is_file():
        return
    try:
        articles = json.loads(news_path.read_text(encoding="utf-8"))
    except Exception:
        return
    if not isinstance(articles, list) or not articles:
        return
    # Determine the most recent date among articles
    dates = []
    polarities = []
    for art in articles:
        pub = art.get("published")
        if not pub:
            continue
        # published is ISO format with Z; strip Z and parse date part
        date_str = pub.split("T")[0]
        dates.append(date_str)
        polarity = art.get("sentiment_polarity")
        if isinstance(polarity, (int, float)):
            polarities.append(polarity)
    if not dates:
        return
    # Use the latest date as the record date
    record_date = max(dates)
    # Average polarity (fallback to 0 if none)
    avg_score = sum(polarities) / len(polarities) if polarities else 0.0
    conn = _connect()
    cur = conn.cursor()
    cur.execute(
        "INSERT OR REPLACE INTO sentiment (ticker, date, score) VALUES (?, ?, ?)",
        (ticker, record_date, avg_score),
    )
    conn.commit()
    conn.close()


def ingest_all(ticker: str, metrics_path: pathlib.Path) -> None:
    """Ingest quantitative, fundamentals and macro data for *ticker*.

    ``metrics_path`` is the path to the ``*_metrics.json`` file produced by ``analyze_report``.
    """
    _ingest_quantitative(metrics_path)
    _ingest_fundamentals(ticker)
    _ingest_macro()
    _ingest_sentiment(ticker)
